# dubbo 配置。参考 https://dubbo.apache.org/zh/docs/references/configuration/xml/
# https://dubbo.apache.org/zh/docs/references/xml/
dubbo:
  # 服务提供者协议配置。对应的配置类： org.apache.dubbo.config.ProtocolConfig。同时，如果需要支持多协议，可以声明多个 <dubbo:protocol> 标签，并在 <dubbo:service> 中通过 protocol 属性指定使用的协议。
  # https://dubbo.apache.org/zh/docs/references/xml/dubbo-protocol/
  protocol:
    name: dubbo # name必填
    port: 2000 # port为可选，dubbo协议缺省端口为20880，rmi协议缺省端口为1099，http和hessian协议缺省端口为80；如果没有配置port，则自动采用默认端口，如果配置为-1，则会分配一个没有被占用的端口。
  application: # 应用信息配置。对应的配置类：org.apache.dubbo.config.ApplicationConfig https://dubbo.apache.org/zh/docs/references/xml/dubbo-application/
    name: user-service # 当前应用名称，用于注册中心计算应用间依赖关系，注意：消费者和提供者应用名不要一样，此参数不是匹配条件，你当前项目叫什么名字就填什么，和提供者消费者角色无关，比如：kylin应用调用了morgan应用的服务，则kylin项目配成kylin，morgan项目配成morgan，可能kylin也提供其它服务给别人使用，但kylin项目永远配成kylin，这样注册中心将显示kylin依赖于morgan
  registry: # 注册中心配置。对应的配置类： org.apache.dubbo.config.RegistryConfig。同时如果有多个不同的注册中心，可以声明多个 <dubbo:registry> 标签，并在 <dubbo:service> 或 <dubbo:reference> 的 registry 属性指定使用的注册中心。 https://dubbo.apache.org/zh/docs/references/xml/dubbo-registry/
    id: user-registry # id可选， 注册中心引用BeanId，可以在<dubbo:service registry="">或<dubbo:reference registry="">中引用此ID
    address: zookeeper://49.232.102.223:2181,49.232.102.223:2182,49.232.102.223:2183,49.232.102.223:2184 # 必填 注册中心服务器地址，如果地址没有端口缺省为9090，同一集群内的多个地址用逗号分隔，如：ip:port,ip:port，不同集群的注册中心，请配置多个<dubbo:registry>标签



